-- شغّل الملف ده مرة واحدة في Supabase SQL Editor
-- بيضيف الوحدات الحقيقية (بدون صور). الصور بتترفع بعد كده من لوحة التحكم.

INSERT INTO public.properties (title,slug,price,area,floor,rooms,bathrooms,direction,view,status,description,location,installments,payment_method,mortgage_available,meters,cover_image) VALUES ('شقة دور أرضي – تكملة أقساط (مقدم 1.3 مليون)','ground-takeover',1300000,115,'الدور الأرضي',3,1,NULL,NULL,'available','شقة 115 متر بـالدور الأرضي، داخل كمبوند سكن مصر بمدينة الإنتاج الإعلامي، قريبة جداً من مول مصر.
تتكون من 3 غرف نوم + ريسبشن + مطبخ + حمام.
جميع العدادات راكبة - السعر قابل للتفاوض.','كمبوند سكن مصر - مدينة الإنتاج الإعلامي','قسط 58 ألف كل 3 شهور لمدة 6 سنين','تكملة أقساط - مقدم 1.300.000',false,'جميع العدادات راكبة','https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.properties (title,slug,price,area,floor,rooms,bathrooms,direction,view,status,description,location,installments,payment_method,mortgage_available,meters,cover_image) VALUES ('شقة 115م² – الدور الأرضي – سكن مصر','ground-1900',1900000,115,'الدور الأرضي',3,1,NULL,NULL,'available','شقة 115 متر بـالدور الأرضي، داخل كمبوند سكن مصر بمدينة الإنتاج الإعلامي، قريبة جداً من مول مصر.
تتكون من 3 غرف نوم + ريسبشن + مطبخ + حمام.
جميع العدادات راكبة - السعر قابل للتفاوض.','كمبوند سكن مصر - مدينة الإنتاج الإعلامي','اتصل للتفاصيل','اتصل للتفاصيل',false,'جميع العدادات راكبة','https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.properties (title,slug,price,area,floor,rooms,bathrooms,direction,view,status,description,location,installments,payment_method,mortgage_available,meters,cover_image) VALUES ('شقة 115م² – الدور الأول أمامي – سكن مصر','first-front-115-landscape',2500000,115,'الدور الأول أمامي',3,1,'بحري شرقي','مميز - لاند سكيب','available','شقة 115 متر بـالدور الأول (أمامي)، داخل كمبوند سكن مصر بمدينة الإنتاج الإعلامي، قريبة جداً من مول مصر.
تتكون من 3 غرف نوم + ريسبشن + مطبخ + حمام.
الاتجاه: بحري شرقي
الفيو: مميز - لاند سكيب
جميع العدادات راكبة - السعر قابل للتفاوض.','كمبوند سكن مصر - مدينة الإنتاج الإعلامي','اتصل للتفاصيل','اتصل للتفاصيل',true,'جميع العدادات راكبة','https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.properties (title,slug,price,area,floor,rooms,bathrooms,direction,view,status,description,location,installments,payment_method,mortgage_available,meters,cover_image) VALUES ('شقة 115م² – الدور الأول أمامي – سكن مصر','first-front-115-2balcony',2500000,115,'الدور الأول أمامي',3,1,'بحري صريح','غير مجروح','available','شقة 115 متر بـالدور الأول (أمامي) بعدد 2 بلكونة، داخل كمبوند سكن مصر بمدينة الإنتاج الإعلامي، قريبة جداً من مول مصر.
تتكون من 3 غرف نوم + ريسبشن + مطبخ + حمام.
الاتجاه: بحري صريح
الفيو: غير مجروح
جميع العدادات راكبة - السعر قابل للتفاوض.','كمبوند سكن مصر - مدينة الإنتاج الإعلامي','اتصل للتفاصيل','اتصل للتفاصيل',false,'جميع العدادات راكبة','https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.properties (title,slug,price,area,floor,rooms,bathrooms,direction,view,status,description,location,installments,payment_method,mortgage_available,meters,cover_image) VALUES ('شقة 115م² – الدور الثاني أمامي – سكن مصر','second-front-115',2450000,115,'الدور الثاني أمامي',3,1,NULL,'عادي','available','شقة 115 متر بـالدور الثاني (أمامي)، داخل كمبوند سكن مصر بمدينة الإنتاج الإعلامي، قريبة جداً من مول مصر.
تتكون من 3 غرف نوم + ريسبشن + مطبخ + حمام.
الفيو: عادي
جميع العدادات راكبة - السعر قابل للتفاوض.','كمبوند سكن مصر - مدينة الإنتاج الإعلامي','اتصل للتفاصيل','اتصل للتفاصيل',false,'جميع العدادات راكبة','https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.properties (title,slug,price,area,floor,rooms,bathrooms,direction,view,status,description,location,installments,payment_method,mortgage_available,meters,cover_image) VALUES ('شقة 118م² – الدور الثالث أمامي – سكن مصر','third-front-118-2balcony',2400000,118,'الدور الثالث أمامي',3,1,'قبلي','ممتاز - على شارع الحديقة المركزية','available','شقة 118 متر بـالدور الثالث (أمامي) بعدد 2 بلكونة، داخل كمبوند سكن مصر بمدينة الإنتاج الإعلامي، قريبة جداً من مول مصر.
تتكون من 3 غرف نوم + ريسبشن + مطبخ + حمام.
الاتجاه: قبلي
الفيو: ممتاز - على شارع الحديقة المركزية','كمبوند سكن مصر - مدينة الإنتاج الإعلامي','اتصل للتفاصيل','اتصل للتفاصيل',false,'غير راكبة','https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.properties (title,slug,price,area,floor,rooms,bathrooms,direction,view,status,description,location,installments,payment_method,mortgage_available,meters,cover_image) VALUES ('شقة 115م² – الدور الثالث أمامي – سكن مصر','third-front-115',2450000,115,'الدور الثالث أمامي',3,1,'قبلي','عادي','available','شقة 115 متر بـالدور الثالث (أمامي)، داخل كمبوند سكن مصر بمدينة الإنتاج الإعلامي، قريبة جداً من مول مصر.
تتكون من 3 غرف نوم + ريسبشن + مطبخ + حمام.
الاتجاه: قبلي
الفيو: عادي
جميع العدادات راكبة - السعر قابل للتفاوض.','كمبوند سكن مصر - مدينة الإنتاج الإعلامي','اتصل للتفاصيل','اتصل للتفاصيل',true,'جميع العدادات راكبة','https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.properties (title,slug,price,area,floor,rooms,bathrooms,direction,view,status,description,location,installments,payment_method,mortgage_available,meters,cover_image) VALUES ('شقة 115م² – الدور الرابع خلفي – سكن مصر','fourth-back-115',2200000,115,'الدور الرابع خلفي',3,1,NULL,NULL,'available','شقة 115 متر بـالدور الرابع (خلفي)، داخل كمبوند سكن مصر بمدينة الإنتاج الإعلامي، قريبة جداً من مول مصر.
تتكون من 3 غرف نوم + ريسبشن + مطبخ + حمام.
جميع العدادات راكبة - السعر قابل للتفاوض.','كمبوند سكن مصر - مدينة الإنتاج الإعلامي','اتصل للتفاصيل','اتصل للتفاصيل',false,'جميع العدادات راكبة','https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.properties (title,slug,price,area,floor,rooms,bathrooms,direction,view,status,description,location,installments,payment_method,mortgage_available,meters,cover_image) VALUES ('شقة 115م² – الدور الخامس أمامي – سكن مصر','fifth-front-115-a',2100000,115,'الدور الخامس أمامي',3,1,NULL,'غير مجروح','available','شقة 115 متر بـالدور الخامس (أمامي)، داخل كمبوند سكن مصر بمدينة الإنتاج الإعلامي، قريبة جداً من مول مصر.
تتكون من 3 غرف نوم + ريسبشن + مطبخ + حمام.
الفيو: غير مجروح
جميع العدادات راكبة - السعر قابل للتفاوض.','كمبوند سكن مصر - مدينة الإنتاج الإعلامي','اتصل للتفاصيل','اتصل للتفاصيل',false,'جميع العدادات راكبة','https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80') ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.properties (title,slug,price,area,floor,rooms,bathrooms,direction,view,status,description,location,installments,payment_method,mortgage_available,meters,cover_image) VALUES ('شقة 115م² – الدور الخامس أمامي – سكن مصر','fifth-front-115-b',2000000,115,'الدور الخامس أمامي',3,1,'بحري','غير مجروح','available','شقة 115 متر بـالدور الخامس (أمامي)، داخل كمبوند سكن مصر بمدينة الإنتاج الإعلامي، قريبة جداً من مول مصر.
تتكون من 3 غرف نوم + ريسبشن + مطبخ + حمام.
الاتجاه: بحري
الفيو: غير مجروح
جميع العدادات راكبة - السعر قابل للتفاوض.','كمبوند سكن مصر - مدينة الإنتاج الإعلامي','اتصل للتفاصيل','اتصل للتفاصيل',false,'جميع العدادات راكبة','https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80') ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.property_features (property_id, feature) SELECT id, '3 غرف + ريسبشن' FROM public.properties WHERE slug='ground-takeover' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='3 غرف + ريسبشن');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قريبة جداً من مول مصر' FROM public.properties WHERE slug='ground-takeover' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قريبة جداً من مول مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'كمبوند سكن مصر' FROM public.properties WHERE slug='ground-takeover' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='كمبوند سكن مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قابل للتفاوض' FROM public.properties WHERE slug='ground-takeover' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قابل للتفاوض');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'جميع العدادات راكبة' FROM public.properties WHERE slug='ground-takeover' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='جميع العدادات راكبة');
INSERT INTO public.property_features (property_id, feature) SELECT id, '3 غرف + ريسبشن' FROM public.properties WHERE slug='ground-1900' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='3 غرف + ريسبشن');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قريبة جداً من مول مصر' FROM public.properties WHERE slug='ground-1900' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قريبة جداً من مول مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'كمبوند سكن مصر' FROM public.properties WHERE slug='ground-1900' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='كمبوند سكن مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قابل للتفاوض' FROM public.properties WHERE slug='ground-1900' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قابل للتفاوض');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'جميع العدادات راكبة' FROM public.properties WHERE slug='ground-1900' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='جميع العدادات راكبة');
INSERT INTO public.property_features (property_id, feature) SELECT id, '3 غرف + ريسبشن' FROM public.properties WHERE slug='first-front-115-landscape' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='3 غرف + ريسبشن');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قريبة جداً من مول مصر' FROM public.properties WHERE slug='first-front-115-landscape' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قريبة جداً من مول مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'كمبوند سكن مصر' FROM public.properties WHERE slug='first-front-115-landscape' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='كمبوند سكن مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'تصلح تمويل عقاري' FROM public.properties WHERE slug='first-front-115-landscape' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='تصلح تمويل عقاري');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قابل للتفاوض' FROM public.properties WHERE slug='first-front-115-landscape' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قابل للتفاوض');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'جميع العدادات راكبة' FROM public.properties WHERE slug='first-front-115-landscape' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='جميع العدادات راكبة');
INSERT INTO public.property_features (property_id, feature) SELECT id, '3 غرف + ريسبشن' FROM public.properties WHERE slug='first-front-115-2balcony' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='3 غرف + ريسبشن');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قريبة جداً من مول مصر' FROM public.properties WHERE slug='first-front-115-2balcony' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قريبة جداً من مول مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'كمبوند سكن مصر' FROM public.properties WHERE slug='first-front-115-2balcony' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='كمبوند سكن مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, '2 بلكونة' FROM public.properties WHERE slug='first-front-115-2balcony' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='2 بلكونة');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قابل للتفاوض' FROM public.properties WHERE slug='first-front-115-2balcony' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قابل للتفاوض');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'جميع العدادات راكبة' FROM public.properties WHERE slug='first-front-115-2balcony' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='جميع العدادات راكبة');
INSERT INTO public.property_features (property_id, feature) SELECT id, '3 غرف + ريسبشن' FROM public.properties WHERE slug='second-front-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='3 غرف + ريسبشن');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قريبة جداً من مول مصر' FROM public.properties WHERE slug='second-front-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قريبة جداً من مول مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'كمبوند سكن مصر' FROM public.properties WHERE slug='second-front-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='كمبوند سكن مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قابل للتفاوض' FROM public.properties WHERE slug='second-front-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قابل للتفاوض');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'جميع العدادات راكبة' FROM public.properties WHERE slug='second-front-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='جميع العدادات راكبة');
INSERT INTO public.property_features (property_id, feature) SELECT id, '3 غرف + ريسبشن' FROM public.properties WHERE slug='third-front-118-2balcony' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='3 غرف + ريسبشن');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قريبة جداً من مول مصر' FROM public.properties WHERE slug='third-front-118-2balcony' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قريبة جداً من مول مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'كمبوند سكن مصر' FROM public.properties WHERE slug='third-front-118-2balcony' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='كمبوند سكن مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, '2 بلكونة' FROM public.properties WHERE slug='third-front-118-2balcony' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='2 بلكونة');
INSERT INTO public.property_features (property_id, feature) SELECT id, '3 غرف + ريسبشن' FROM public.properties WHERE slug='third-front-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='3 غرف + ريسبشن');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قريبة جداً من مول مصر' FROM public.properties WHERE slug='third-front-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قريبة جداً من مول مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'كمبوند سكن مصر' FROM public.properties WHERE slug='third-front-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='كمبوند سكن مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'تصلح تمويل عقاري' FROM public.properties WHERE slug='third-front-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='تصلح تمويل عقاري');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قابل للتفاوض' FROM public.properties WHERE slug='third-front-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قابل للتفاوض');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'جميع العدادات راكبة' FROM public.properties WHERE slug='third-front-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='جميع العدادات راكبة');
INSERT INTO public.property_features (property_id, feature) SELECT id, '3 غرف + ريسبشن' FROM public.properties WHERE slug='fourth-back-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='3 غرف + ريسبشن');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قريبة جداً من مول مصر' FROM public.properties WHERE slug='fourth-back-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قريبة جداً من مول مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'كمبوند سكن مصر' FROM public.properties WHERE slug='fourth-back-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='كمبوند سكن مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قابل للتفاوض' FROM public.properties WHERE slug='fourth-back-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قابل للتفاوض');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'جميع العدادات راكبة' FROM public.properties WHERE slug='fourth-back-115' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='جميع العدادات راكبة');
INSERT INTO public.property_features (property_id, feature) SELECT id, '3 غرف + ريسبشن' FROM public.properties WHERE slug='fifth-front-115-a' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='3 غرف + ريسبشن');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قريبة جداً من مول مصر' FROM public.properties WHERE slug='fifth-front-115-a' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قريبة جداً من مول مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'كمبوند سكن مصر' FROM public.properties WHERE slug='fifth-front-115-a' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='كمبوند سكن مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قابل للتفاوض' FROM public.properties WHERE slug='fifth-front-115-a' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قابل للتفاوض');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'جميع العدادات راكبة' FROM public.properties WHERE slug='fifth-front-115-a' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='جميع العدادات راكبة');
INSERT INTO public.property_features (property_id, feature) SELECT id, '3 غرف + ريسبشن' FROM public.properties WHERE slug='fifth-front-115-b' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='3 غرف + ريسبشن');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قريبة جداً من مول مصر' FROM public.properties WHERE slug='fifth-front-115-b' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قريبة جداً من مول مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'كمبوند سكن مصر' FROM public.properties WHERE slug='fifth-front-115-b' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='كمبوند سكن مصر');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'قابل للتفاوض' FROM public.properties WHERE slug='fifth-front-115-b' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='قابل للتفاوض');
INSERT INTO public.property_features (property_id, feature) SELECT id, 'جميع العدادات راكبة' FROM public.properties WHERE slug='fifth-front-115-b' AND NOT EXISTS (SELECT 1 FROM public.property_features pf WHERE pf.property_id=properties.id AND pf.feature='جميع العدادات راكبة');
